### ISSUE TITLE
Unstable codecov workflow

### ISSUE THREAD

**Issue by timobrembeck** [sphinx-doc/sphinxcontrib-django#34]
The upload of the code coverage seems to be very unstable, I had to re-run the jobs multiple times today:

```
Error: Codecov: Failed to properly upload: The process '/Users/runner/work/_actions/codecov/codecov-action/v3/dist/codecov' failed with exit code 255
```

This seems to be related to this issue: https://github.com/codecov/codecov-action/issues/598

One suggestion is to generate a secret token and use this despite the repo being public.

Unfortunately, we have a bottleneck here: @vdboor, you are the only person who can access the codecov administration settings since they manage the permissions per organization.

@vdboor would it be ok for you if I'd transfer ownership of this repository e.g. to the @jazzband organization to ensure maintenance in the long term?

**Comment by insspb** [comment]
@timoludwig maybe to sphinx? as it is sphinx related project.

**Comment by timobrembeck** [comment]
@AA-Turner You seem to maintain a few sphinx extensions under the umbrella of the @sphinx-doc organization, do you think it might be possible to transfer this repository as well?

I would still maintain this project, it's just about the GitHub ownership and specific administrative tasks. Of course I could just transfer the repo to my personal account, I just thought it would make sense to have the repo under an organization which also encourages more support from the community...

**Comment by AA-Turner** [comment]
Fine by me, I'd also ask that the Sphinx team is added to PyPI (we have a 'Sphinx' organisation on PyPI to manage all the packages, you'd still be able to publish releases of course.).

I'll need to temporarily add you to the Sphinx-Doc org so that you can do the transfer, what time would work for you tomorrow so that we could do it semi synchronously?

A

**Comment by timobrembeck** [comment]
Great, thanks! Tomorrow around 12:00 UTC should be fine.

I just noticed that there is also the organization @sphinx-contrib with less restrictive member policies, maybe this would be an even better option?

**Comment by AA-Turner** [comment]
Works for me, thanks.

Sphinx-Doc vs Sphinx-Contrib -- up to you entirely, though the core Sphinx team isn't involved in Sphinx-Contrib.

There's part of me that would like to see a greater ecosystem integration for Sphinx (eg how Pytest or Tox have all their plugins together), but this would be a tremendous organisational effort!

A

**Comment by AA-Turner** [comment]
Works for me, thanks.

Sphinx-Doc vs Sphinx-Contrib -- up to you entirely, though the core Sphinx team isn't involved in Sphinx-Contrib.

There's part of me that would like to see a greater ecosystem integration for Sphinx (eg how Pytest or Tox have all their plugins together), but this would be a tremendous organisational effort!

A

**Comment by timobrembeck** [comment]
Alright, let's go with the official Sphinx orga then :wink:

Oh, but one obstacle I just got aware of: Codecov [does not seem to work well with the transfer](https://codecov.freshdesk.com/support/solutions/articles/43000629044-repo-not-updating-after-transfer-rename) and apparently the repo needs to be set up again - including installing the Codecov app in the new owner organization... Is this something the Sphinx core team would be ok with, or are you against the integration of third party services?

I could also understand if you're trying to keep the official organization clean of such integrations, but at the moment I don't have time to migrate the code coverage measurement into a GitHub-Actions-only setup, so in that case I'd use my personal account for the time being and try to come up with a long term solution by the end of the year...

**Comment by AA-Turner** [comment]
We have a codecov.io integration already: https://app.codecov.io/gh/sphinx-doc/sphinx, so this'll be fine

A

**Comment by AA-Turner** [comment]
I've just sent you the invitation to @sphinx-doc.

A

**Comment by timobrembeck** [comment]
@AA-Turner Thanks, the repo transfer worked as expected, I also set up the new codecov integration now.

I didn't succeed in adding the Sphinx orga as maintainer on PyPI, I can only select usernames there. Do you know what I need to do there?

**Comment by AA-Turner** [comment]
Can you add me please (AA-Turner), I can then add the org?

A

**Comment by AA-Turner** [comment]
Also, you're currently the only admin for this repo, is there anyone else we should add back with commit or admin access?

A

**Comment by AA-Turner** [comment]
Transferred: https://pypi.org/project/sphinxcontrib-django/; https://pypi.org/org/Sphinx/

A

**Comment by timobrembeck** [comment]
Great, thanks for your help and the quick responses! :heart: 

> Also, you're currently the only admin for this repo, is there anyone else we should add back with commit or admin access?

No, there are no other maintainers since @vdboor stepped down, but maybe the new ownership attracts more people who want to get involved with the project.

@vdboor let us know if you want to keep admin access for this project!
